# Generated by Django 4.0.5 on 2022-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(verbose_name='?')),
                ('published_date', models.DateTimeField(verbose_name={'DONT_ACCEPT_BLANKLINE': 2, 'DONT_ACCEPT_TRUE_FOR_1': 1, 'ELLIPSIS': 8, 'FAIL_FAST': 1024, 'IGNORE_EXCEPTION_DETAIL': 32, 'NORMALIZE_WHITESPACE': 4, 'REPORT_CDIFF': 128, 'REPORT_NDIFF': 256, 'REPORT_ONLY_FIRST_FAILURE': 512, 'REPORT_UDIFF': 64, 'SKIP': 16})),
            ],
        ),
    ]
